name: biof-proj
channels:
  - bioconda
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - dropbox
  - graphviz=2.40.1
  - numpy
  - numpy-base
  - python=3.6.13
  - snakemake
  - r-base=4.1.1
